import type { Metadata } from "next";
import { IBM_Plex_Sans } from 'next/font/google'
import "./globals.css";

const Plex_Sans = IBM_Plex_Sans({
  weight: '200',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Plex_Sans.className}>{children}</body>
    </html>
  );
}
